apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: gomud
build:
  artifacts:
  - image: web
    context: $GOPATH\src\github.com\labiraus\gomud-web
    docker:
      dockerfile: dockerfile
  - image: mud
    context: $GOPATH\src\github.com\labiraus\gomud-mud
    docker:
      dockerfile: dockerfile
  - image: user
    context: $GOPATH\src\github.com\labiraus\gomud-user
    docker:
      dockerfile: dockerfile
  - image: postgres-init
    context: ./postgres
    docker:
      dockerfile: dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/gomud.yml
    - kubernetes/database.yml
