apiVersion: v1
kind: Namespace
metadata:
  name: gomud
  "annotations": { linkerd.io/inject: enabled }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gomud
  labels:
    app: db-postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gomud
  name: postgres-pv-volume
  labels:
    type: local
    app: db-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: gomud
  name: postgres-pv-claim
  labels:
    app: db-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db-postgres
  namespace: gomud
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: postgres
          image: postgres-init:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: gomud
  name: service-db-postgres
  labels:
    app: db-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: db-postgres