FROM golang:alpine

RUN apk add protoc
RUN apk add git
RUN apk add python3

WORKDIR /home

RUN git clone https://github.com/labiraus/gomud-common.git

WORKDIR /home/gomud-common

COPY protogen.py /usr/local/bin

RUN git config pull.rebase false

ENTRYPOINT git config pull.rebase false | python3 /usr/local/bin/protogen.py