CREATE USER gomud PASSWORD 'admin123';
CREATE DATABASE gomud;
GRANT ALL PRIVILEGES ON DATABASE gomud TO gomud;

\c gomud;

CREATE TABLE public.connections
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    room_id integer NOT NULL,
    neighbour_id integer NOT NULL,
    dir integer NOT NULL,
    two_way boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE public.rooms
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    description character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_name character varying NOT NULL,
    character_name character varying NOT NULL,
    password_hash character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

INSERT INTO rooms (id, name, description) VALUES 
(1, 'The Beginning', 'This is where everything starts from'),
(2, 'The End', 'You have reached the end of the world');

INSERT INTO connections (room_id, neighbour_id, dir, two_way) VALUES
(1, 2, 2, TRUE);
